name: Build

on: 
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet build -c Release src/LogitechSdkListener/LogitechSdkListener.csproj
